apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: todo
type: Opaque
stringData:
  DB_USER: appuser
  DB_PASS: apppass
  DB_ROOT_PASS: adminpass
  MONGODB_ROOT_PASSWORD: adminpass
  MONGODB_PASSWORD: apppass
  MONGODB_DATABASE: test
  MONGODB_USERNAME: appuser